apiVersion: v1
kind: Secret
metadata:
  name: security-secrets
  namespace: nexoryx-security
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: CHANGE_ME
  VPN_PRIVATE_KEY: CHANGE_ME
  VPN_PUBLIC_KEY: CHANGE_ME
